---
title: "week02_JZ"
author: "Jinxiao Zhang"
date: "January 15, 2019"
output: html_document
---

```{r lead libraries}
library(tidyverse)
library(rethinking)
```

```{r lecture}
data("Howell1")
d <- Howell1
precis(d)


sample_mu <- rnorm( 1e4 , 178 , 20 ) 
sample_sigma <- runif( 1e4 , 0 , 50 )
prior_h <- rnorm( 1e4 , sample_mu , sample_sigma )
dens( prior_h )


#### grid approximation #####
d2 <- d[ d$age >= 18 , ]
mu.list <- seq( from=153.5, to=155 , length.out=150 ) 
sigma.list <- seq( from=7 , to=8.5 , length.out=150 )
post <- expand.grid( mu=mu.list , sigma=sigma.list )
#calculate the log-likelihood
post$LL <- sapply( 1:nrow(post) , function(i) sum( dnorm(
  d2$height,
  mean=post$mu[i] ,
  sd=post$sigma[i] ,
  log=TRUE) ) )
#add up the log-likelihood
post$prod <- post$LL +
  dnorm( post$mu , 178 , 20 , TRUE ) +
  dunif( post$sigma , 0 , 50 , TRUE ) # the priors
post$prob <- exp(( post$prod - max(post$prod)))

# visualize
#contour_xyz( post$mu , post$sigma , post$prob)
image_xyz( post$mu , post$sigma , post$prob )


sample.rows <- sample( 1:nrow(post) , size=1e4 , replace=TRUE ,
prob=post$prob )
sample.mu <- post$mu[ sample.rows ]
sample.sigma <- post$sigma[ sample.rows ]

plot( sample.mu , sample.sigma , cex=0.5 , pch=16 , col=col.alpha(rangi2,0.1) )
dens( sample.mu )
dens( sample.sigma )


########### Quardratic approximation ###########
flist <- alist(
height ~ dnorm( mu , sigma ) ,
mu ~ dnorm( 178 , 20 ) ,
sigma ~ dunif( 0 , 50 )
)
m4.1 <- quap( flist , data=d2)

post <- extract.samples( m4.1 , n=1e4 )
head(post)
dens(post$mu)

############# linear regression ############
# define the average weight, x-bar
xbar <- mean(d2$weight)
# fit model
m4.3 <- quap(
alist(
height ~ dnorm( mu , sigma ) ,
mu <- a + b*( weight - xbar ) ,
# the priors of the parameters
a ~ dnorm( 178 , 20 ) ,
b ~ dlnorm( 0 , 1 ) ,
sigma ~ dunif( 0 , 50 )
) ,
data=d2 )

precis(m4.3)

plot( height ~ weight , data=d2 , col=rangi2 )
post <- extract.samples( m4.3 )
a_map <- mean(post$a)
b_map <- mean(post$b)
curve( a_map + b_map*(x - xbar) , add=TRUE )

ggplot(post, aes(a, b) ) +
  geom_bin2d(bins = 70) +
  theme_bw()
```

```{r}

#### my testing on generating samples ########
set.seed(100)
tmp <- rnorm(10000, 10:19, 1)
dens(tmp)

tmp1 <- c()
for (n in 10:19){
  tmp1 <- c(tmp1, rnorm(1000, n, 1))
}
dens(tmp1)
```
```{r Q1}
data(Howell1)
d <- Howell1
d2 <- d[d$age >= 18,]

weight_mean = mean(d2$weight)

# fit the model
m1 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <-  alpha +beta*(weight - weight_mean),
    alpha ~ dnorm(178, 20),
    beta ~ dlnorm(0, 1),
    sigma ~ dunif(0, 50)
  ),
  data = d2
)

precis(m1)

post <- extract.samples(m1)

# predict mu
mu_45 <- post$alpha + post$beta*(45 - weight_mean)
mu_45 <- link(m1, data = data.frame(weight = c(45, 40, 60, 31, 53)))
apply(mu_45, 2, mean)
apply(mu_45, 2, PI, prob = .89)
## wrong ######
## link doesn't work here, because it only predicts the mu, not the height...
## same mean, but different variance 

# from solutions
dat <- data.frame( weight=c(45,40,65,31,53) )
h_sim <- sim( m1 , data=dat )
Eh <- apply(h_sim,2,mean)
h_ci <- apply(h_sim,2,PI,prob=0.89)
```

```{r  Q2}
d <- d %>% 
  mutate(weight_scd = scale(weight),
         log_weight_scd = scale(log(weight)))


# fit a quadratic model
m2 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <-  alpha + beta1*log_weight_scd + beta2*I(log_weight_scd^2),
    alpha ~ dnorm(178, 20),
    beta1 ~ dlnorm(0, 1),
    beta2 ~ dnorm(0, 1),
    sigma ~ dunif(0, 50)
  ),
  data = d
)

precis(m2)
post2 <- extract.samples(m2)

m2_sim <- sim(m2, data = data.frame(log_weight_scd = d$log_weight_scd))
m2_predict <- data.frame(height = apply(m2_sim,2,mean), weight = d$weight)


mu_ci <- apply(m2_sim,2,PI,0.99)

# plot the model vs. the data
ggplot(d, aes(weight, height))+
  geom_point(shape = 21,
             color = "blue")+
  geom_line(data = m2_predict, 
             aes(weight, 
                 height),
            size = 1)


```
```{r Q3}
# d <- Howell1
  
# d$weight_s <- ( d$weight - mean(d$weight) )/sd(d$weight)
# d$weight_s2 <- d$weight_s^2
# m4.5 <- quap(
#   alist(
#     height ~ dnorm( mu , sigma ) ,
#     mu <- a + b1*weight_s + b2*weight_s2 ,
#     a ~ dnorm( 178 , 20 ) ,
#     b1 ~ dlnorm( 0 , 1 ) ,
#     b2 ~ dnorm( 0 , 1 ) ,
#     sigma ~ dunif( 0 , 50 )
#   ) ,
#   data=d )

# plot the prior
set.seed(1)
N <- 100 # 100 lines
a <- rnorm( N , 178 , 20 )
b1 <- rlnorm( N , 0 , 1)
b2 <- rlnorm(N, -5, 1)
#b2 <- rexp(N, 10)

plot( NULL , xlim=range(d2$weight) , ylim=c(-100,400) ,
xlab="weight" , ylab="height" )
abline( h=0 , lty=2 )
abline( h=272 , lty=1 , lwd=0.5 )
xbar <- mean(d$weight)
for ( i in 1:N ) curve( a[i] + b1[i]*(x - xbar) + b2[i]*(x - xbar)^2,
from=min(d2$weight) , to=max(d2$weight) , add=TRUE , 
col=col.alpha("black",0.3) )
```
```{r plot log-normal distribution}
x = seq(0, 0.05, by = .0001)
y = dlnorm(x, -5, 1)
plot(x, y)

x = rlnorm(10000, -5, 1)
dens(x)
dens(log(x))
```



